// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "498545b4-053d-49d1-9d7f-548d689357b9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onInnerStripColorChange();
void onOuterStripColorChange();
void onSmallStripColorChange();

CloudColor innerStripColor;
CloudColor outerStripColor;
CloudColor smallStripColor;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);  
  ArduinoCloud.addProperty(innerStripColor, READWRITE, ON_CHANGE, onInnerStripColorChange);
  ArduinoCloud.addProperty(outerStripColor, READWRITE, ON_CHANGE, onOuterStripColorChange);
  ArduinoCloud.addProperty(smallStripColor, READWRITE, ON_CHANGE, onSmallStripColorChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
