name: Compile Arduino Sketches

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Arduino sketch
      uses: arduino/compile-sketches@v1
      with:
        fqbn:  |
          - "arduino:avr:mega"
          - "arduino:avr:uno"
          - "esp32:esp32:esp32"
          - "esp8266:esp8266:generic"
        sketch-paths: |
          - ./
        libraries: |
         - name: "Adafruit NeoPixel"
